/*
 This file was generated by Dashcode and is covered by the
 license.txt included in the project.  You may edit this file,
 however it is recommended to first turn off the Dashcode
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "bottomRectangleShape": { "creationFunction": "CreateShape", "leftImageWidth": 12, "rightImageWidth": 12, "view": "DC.View" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done", "view": "DC.View" },
    "image": { "view": "DC.ImageLayout" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack", "view": "DC.View" },
    "scrollArea": { "autoHideScrollbars": true, "creationFunction": "CreateScrollArea", "hasVerticalScrollbar": true, "scrollbarDivSize": 18, "scrollbarMargin": 6, "spacing": 4, "view": "DC.View" },
    "sectionMenu": { "creationFunction": "CreatePopupButton", "leftImageWidth": 11, "onchange": "displayContent", "options": ["All", ["Starting", "starting.html"], ["Stopping", "stopping.html"], ["Getting Help", "getting_help.html"], ["Execution Context", "execution_context.html"], ["Execution Control", "execution_control.html"], ["Breakpoints and Watchpoints", "breakpoints_and_watchpoints.html"], ["Program Stack", "program_stack.html"], ["Shell", "shell.html"], ["Display/Inspect", "display_inspect.html"], ["Automatic Display", "automatic_display.html"], ["Expressions", "expressions.html"], ["Symbol Table", "symbol_table.html"], ["Signal Handling", "signal_handling.html"], ["Debugging Targets", "debugging_targets.html"], ["Controlling GDB", "controlling_gdb.html"], ["Working Files", "working_files.html"], ["Source Files", "source_files.html"], ["Emacs", "emacs.html"]], "rightImageWidth": 16 },
    "title": { "text": "GNU Debugger Commands:", "view": "DC.Text" },
    "topRectangleShape": { "creationFunction": "CreateShape", "leftImageWidth": 12, "rightImageWidth": 12, "view": "DC.View" }
};





















